apiVersion: v1
kind: Service
metadata:
  name: envoy
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    run: envoy
  type: LoadBalancer
  loadBalancerIP: 35.230.84.125
