apiVersion: v1
kind: Service
metadata:
  name: zipkin
spec:
  clusterIP: "None"
  ports:
  - port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    run: zipkin
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
